

exports.SDBG_SUBMIT_BY_VENDOR = "SDBG_SUBMIT_BY_VENDOR";
exports.SDBG_SUBMIT_BY_GRSE = "SDBG_SUBMIT_BY_GRSE";
exports.SDBG_ACKNOWLEDGE_BY_GRSE = "SDBG_ACKNOWLEDGE_BY_GRSE";
exports.DRAWING_SUBMIT_BY_VENDOR = "DRAWING_SUBMIT_BY_VENDOR";
exports.DRAWING_SUBMIT_BY_GRSE = "DRAWING_SUBMIT_BY_GRSE";
exports.DRAWING_APPROVED_BY_GRSE = "DRAWING_APPROVED_BY_GRSE";
exports.QAP_SUBMIT_BY_VENDOR = "QAP_SUBMIT_BY_VENDOR";
exports.QAP_SUBMIT_BY_GRSE = "QAP_SUBMIT_BY_GRSE";
exports.QAP_APPROVED_BY_GRSE = "QAP_APPROVED_BY_GRSE";
exports.QAP_ASSIGN_BY_GRSE = "QAP_ASSIGN_BY_GRSE";
exports.VENDOR_REMINDER_EMAIL = "VENDOR_REMINDER_EMAIL";
exports.PO_UPLOAD_IN_LAN_NIC = "PO_UPLOAD_IN_LAN_NIC";